version: '3'
services:
  nginx:
    depends_on:
        - api
        - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  postgres:
    depends_on:
      - api
    image: 'postgres:latest'
    command: postgres
    volumes:
      - ./backup:/var/backup
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres_password
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - ./server:/app
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app